
    const data = [

        {
           imageUrl:require("./image/s1.jpg"),
            banner:'20%',
            title:'Advent Leather Bag.....',
            text:'1pc(s)',
            oldprice:'$100',
            price:'160',
            cart:'Cart',    
        },
        {
            imageUrl:require("./image/nice2.jpg"),
             banner:'20%',
             title:'Gucci Leather Bag.....',
             text:'1pc(s)',
             oldprice:'$70',
             price:'100',
             cart:'Cart',    
         },
         {
            imageUrl:require("./image/bag3.jpg"),
             banner:'20%',
             title:'Lolipop Purse.....',
             text:'1pc(s)',
             oldprice:'$100',
             price:'110',
             cart:'Cart',    
         }
         ,
         {
            imageUrl:require("./image/s3.jpg"),
             banner:'20%',
             title:'Chick & Sticks Bag.....',
             text:'1pc(s)',
             oldprice:'$100',
             price:'80',
             cart:'Cart',    
         },
         {
            imageUrl:require("./image/bag1.jpg"),
             banner:'10%',
             title:'Calvin Klien Extreme.....',
             text:'1pc(s)',
             oldprice:'$25',
             price:'200',
             cart:'Cart',    
         },
         {
            imageUrl:require("./image/bag2.jpg"),
             banner:'90%',
             title:'EL-Bush Collection...',
             text:'1pc(s)',
             oldprice:'$200',
             price:'110',
             cart:'Cart',    
         }
         ,
         {
            imageUrl:require("./image/bag6.jpg"),
             banner:'20%',
             title:'Meldini Adalfo Classic.....',
             text:'1pc(s)',
             oldprice:'$100',
             price:'110',
             cart:'Cart',    
         }
         ,
         {
            imageUrl:require("./image/bag5.jpg"),
             banner:'',
             title:'Gorgio Amani Classic.....',
             text:'1pc(s)',
             oldprice:'',
             price:'300',
             cart:'Cart',    
         },
         {
            imageUrl:require("./image/bag4.jpg"),
             banner:'20%',
             title:'Micheal Kors Bags.....',
             text:'1pc(s)',
             oldprice:'$150',
             price:'130',
             cart:'Cart',    
         },
         {
            imageUrl:require("./image/bag7.webp"),
             banner:'10%',
             title:'New Classic Bags.....',
             text:'1pc(s)',
             oldprice:'$120',
             price:'110',
             cart:'Cart',    
         },
         {
            imageUrl:require("./image/bag8.jpg"),
             banner:'20%',
             title:'Armani Leather Bag.....',
             text:'1pc(s)',
             oldprice:'$70',
             price:'50',
             cart:'Cart',    
         },
         {
            imageUrl:require("./image/bag9.jpg"),
             banner:'20%',
             title:'Sexy Bags.....',
             text:'1pc(s)',
             oldprice:'$100',
             price:'110',
             cart:'Cart',    
         },
    ] 

export default data;